name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build Electron App
        run: pnpm run build

      - name: Package Electron App for Linux
        run: pnpm run package-linux

      - name: Package Electron App for Windows
        run: pnpm run package-win
