name: Build Electron App

permissions:
  contents: write
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Electron App (Linux)
        run: pnpm run package -p linux -a x64

      - name: Build Electron App (Windows)
        run: pnpm run package -p win32 -a x64

      - name: Remove Old Artifacts
        run: |
          gh api -X GET "/repos/${{ github.repository }}/actions/artifacts" \
            -q ".artifacts[] .id" | \
          while read it; do
            gh api -X DELETE "/repos/${{ github.repository }}/actions/artifacts/$it"
          done

      - name: Compress Build Artifacts
        run: |
          tar -czvf mbkm.tar.gz -C ./out mbkm

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mbkm
          path: mbkm.tar.gz
